name : build and test 
on:
push:
 branches: 
    - main
pull_request: 
 branches: {main}
jobs:
 build:
 runs-on: ubuntu-latest 
 strategy:
 matrix: 
  node version: {18x}
 steps:
  - uses: action/checkout@v4
  - name: use node.js ${{ matrix.node-version }}
    uses: actions/setup-node@v4
    with:
     node-version:  ${{ matrix.node-version }}
  
