name : build and test 
on: push
branches: {main}
pull request: 
branches:{main}
job:
build:
run on : ubantu latest 
strategy:
node version {18x}
step:
uses: action/checkout@v4
name: use node.js{matrix.node-version}
uses: action setup node@v4
with: